### ISSUE TITLE
With recent TypeScript, frequent "Could not find sourceFile" on few first requests after startup

### ISSUE THREAD

**Issue by mickaelistria** [theia-ide/typescript-language-server#109]
I'm trying to migrate Eclipse Wild Web Developer to newer stack (TypeScript, typescript-language-server, angular-language-service).
Overall, it seems to work fine, but I found that with recent versions of TypeScript, the language-server often fails at processing the first requests, with a message like

```
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request textDocument/completion failed with message: Error processing request. Could not find sourceFile: '/home/mistria/sandbox/angular-demo/dummy.ts' in [].
Error: Could not find sourceFile: '/home/mistria/sandbox/angular-demo/dummy.ts' in [].
    at getValidSourceFile (/home/mistria/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/language-servers/node_modules/typescript/lib/tsserver.js:121859:23)
    at Object.getCompletionsAtPosition (/home/mistria/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/language-servers/node_modules/typescript/lib/tsserver.js:122085:80)
    at Object.proxy.getCompletionsAtPosition (/home/mistria/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/language-servers/node_modules/@angular/language-service/bundles/language-service.umd.js:47922:30)
    at Proxy.rest (/home/mistria/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/language-servers/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:84:24)
    at IOSession.Session.getCompletions (/home/mistria/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/language-servers/node_modules/typescript/lib/tsserver.js:131119:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/home/mistria/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/language-servers/node_modules/typescript/lib/tsserver.js:130072:61)
    at /home/mistria/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/language-servers/node_modules/typescript/lib/tsserver.js:131637:88
    at IOSession.Session.executeWithRequestId (/home/mistria/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/language-servers/node_modules/typescript/lib/tsserver.js:131628:28)
    at IOSession.Session.executeCommand (/home/mistria/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/language-servers/node_modules/typescript/lib/tsserver.js:131637:33)
    at IOSession.Session.onMessage (/home/mistria/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/language-servers/node_modules/typescript/lib/tsserver.js:131659:35)
    at Interface.<anonymous> (/home/mistria/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/language-servers/node_modules/typescript/lib/tsserver.js:132950:27)
    at Interface.emit (events.js:189:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
Opening some other file in the same project and trying to edit it works fine with the same language server instance; and sometimes, coming back to initial file or closing/reopening it fixes the issue and makes the LS functional and that initial file.

**Comment by rchl** [comment]
There is not enough information here to investigate it. We would need full server communication up to this point.

Since this is an old issue and might no longer be possible to reproduce I'll go ahead and close it.

If it's definitively still an issue and server communication can be provided then we can re-open.
