### ISSUE TITLE
Does this work with tsx and react?

### ISSUE THREAD

**Issue by Luis-Hebendanz** [theia-ide/typescript-language-server#138]
Hello,

Does this language server work with tsx files and react? Because I couldn't get it to work :/

This tsconfig.json works with javascript-typescript-langserver 
```
{
"compilerOptions": {
    "lib": ["es6", "dom"],
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "jsx": "react",
    "typeRoots": [
        "types"
    ],
    "paths": {
        "~*": ["./*"]
    },
},
"include": [
    "app/frontend/**/*"
]
}

```

**Comment by jeffvandyke** [comment]
Is `tsserver` available on your `PATH`? Having typescript installed as a global npm package was my main mistake these last 2 times.

**Comment by jeffvandyke** [comment]
I'd have to know a bit more about your setup to offer any further assistance. What's your text editor? Have you configured typescript-language-server to be the chosen language server for the filetype for `.tsx` files? I have TypeScript + React working using this plugin, so I'm not sure what your particular issue is.

**Comment by wujiang** [comment]
I'm struggling with setting this up with `emacs 26.3` as well. `typescript@3.7.5` was installed globally. OS is `openbsd 6.6`. An error message I got is:

```
LSP :: Request textDocument/completion failed with message: Error processing request. Cannot read property 'getSourceFile' of undefined
TypeError: Cannot read property 'getSourceFile' of undefined
    at getValidSourceFile (/usr/local/lib/node_modules/typescript/lib/tsserver.js:130560:38)
    at Object.getCompletionsAtPosition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:130808:80)
    at IOSession.Session.getCompletions (/usr/local/lib/node_modules/typescript/lib/tsserver.js:140445:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:139428:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:140960:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:140951:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:140960:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:140983:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:142298:27)
    at Interface.emit (events.js:198:13)
    at Interface._onLine (readline.js:308:10)
    at Interface._normalWrite (readline.js:451:12)
    at Socket.ondata (readline.js:165:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by Luis-Hebendanz** [comment]
> Is `tsserver` available on your `PATH`? Having typescript installed as a global npm package was my main mistake these last 2 times.

Yes `tsserver` is available in my `PATH` is this a problem? 
I am using [`kakoune`](https://github.com/mawww/kakoune) with the `kak-lsp` plugin.
The language server gets started from the plugin like this:
https://github.com/ul/kak-lsp/wiki/How-to-install-servers#typescript

**Comment by schemar** [comment]
You can find the fix here: https://github.com/ul/kak-lsp/issues/211

In addition to `typescript`, set up the language server to be used with `tsx` like so:

```
[language.tsx]
filetypes = ["typescript"]
roots = ["package.json"]
offset_encoding = "utf-8"
command = "typescript-language-server"
args = ['--stdio']
```
