### ISSUE TITLE
language server crashes on a syntax error in globby

### ISSUE THREAD

**Issue by mendess** [theia-ide/typescript-language-server#243]
stderr is:
```
/usr/lib/node_modules/typescript-language-server/node_modules/globby/index.js:28
	} catch {
	        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/typescript-language-server/node_modules/del/index.js:4:16)

```
I don't know what is causing this but it happens in `0.5.2` and `0.5.4`

**Comment by rchl** [comment]
Probably your node version is tool old. You need v10 or v12 at least, I'm not sure now.
