### ISSUE TITLE
[theia] `Error: No Project` when refreshing the browser for Theia

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/typescript-language-server#86]
The Theia WS root was Theia. Got this when I refreshed the browser:
```
root ERROR Error from definitions request: file:///Users/akos.kitta/git/theia/packages/core/src/browser/keybinding.ts#159/4 Error: Request textDocument/definition failed with message: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/akos.kitta/git/theia/node_modules/typescript/lib/tsserver.js:92289:23)
    at ProjectService.getDefaultProjectForFile (/Users/akos.kitta/git/theia/node_modules/typescript/lib/tsserver.js:94518:46)
    at IOSession.Session.getFileAndProjectWorker (/Users/akos.kitta/git/theia/node_modules/typescript/lib/tsserver.js:96934:87)
    at IOSession.Session.getFileAndProject (/Users/akos.kitta/git/theia/node_modules/typescript/lib/tsserver.js:96919:29)
    at IOSession.Session.getDefinition (/Users/akos.kitta/git/theia/node_modules/typescript/lib/tsserver.js:96572:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/akos.kitta/git/theia/node_modules/typescript/lib/tsserver.js:96044:61)
    at /Users/akos.kitta/git/theia/node_modules/typescript/lib/tsserver.js:97580:88
    at IOSession.Session.executeWithRequestId (/Users/akos.kitta/git/theia/node_modules/typescript/lib/tsserver.js:97571:28)
    at IOSession.Session.executeCommand (/Users/akos.kitta/git/theia/node_modules/typescript/lib/tsserver.js:97580:33)
    at IOSession.Session.onMessage (/Users/akos.kitta/git/theia/node_modules/typescript/lib/tsserver.js:97600:35)
    at Interface.<anonymous> (/Users/akos.kitta/git/theia/node_modules/typescript/lib/tsserver.js:98831:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:280:10)
    at Interface._normalWrite (readline.js:422:12)
    at Socket.ondata (readline.js:139:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:597:20)
    at new ResponseError (http://localhost:3000/bundle.js:81279:28)
    at handleResponse (http://localhost:3000/bundle.js:80260:48)
    at processMessageQueue (http://localhost:3000/bundle.js:80088:17)
    at http://localhost:3000/bundle.js:80072:13
    at run (http://localhost:3000/bundle.js:77955:13)
    at runIfPresent (http://localhost:3000/bundle.js:77984:21)
    at onGlobalMessage (http://localhost:3000/bundle.js:78024:17)
```

Reproducibility: it happens sometimes.

**Comment by kittaakos** [comment]
Similar (if not the same): https://github.com/theia-ide/typescript-language-server/issues/60

**Comment by apexskier** [comment]
I think this can be closed, given Theia doesn't use this dependency any more.
