### ISSUE TITLE
Make timeouts configurable / possible to disable

### ISSUE THREAD

**Issue by felixfbecker** [theia-ide/typescript-language-server#91]
It seems like there is a hardcoded timeout for every request.
When running `yarn` while the server is running, it seems like tsserver gets overwhelmed with handling all the new files added and doesn't respond to requests immediatly.
I then get a lot of errors like:
```
Error: Request textDocument/definition failed with message: definition timeout
    at handleResponse (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.setImmediate (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/vscode-jsonrpc/lib/main.js:247:13)
```

**Comment by felixfbecker** [comment]
I set the tsserver loglevel to `verbose` and it's clear that the server is just swamped with all the file watch events.

**Comment by rchl** [comment]
The hardcoded timeout was removed in b9cf57816ca07b9b3f3631130b7b5250b0db7ced
